/* Evidence-based event rules shared by the existing reports. */
(()=>{
const coverage=s=>s?.max_organic_rank??s?.coverage??s?.returned??0;
const normal=u=>{if(!u)return '';try{const x=new URL(u);x.hash='';for(const k of [...x.searchParams.keys()])if(/^(utm_|srsltid$|gclid$|fbclid$|msclkid$)/i.test(k))x.searchParams.delete(k);x.searchParams.sort();return x.toString().replace(/\/$/,'');}catch{return u;}};
const time=s=>Date.parse((s||'').replace(' ','T').replace(/ ([+-])/,'$1'));
const found=(s,c)=>(s?.organic||[]).filter(o=>o.rank>0&&o.rank<=40&&c.domains.some(d=>o.domain===d||o.domain.endsWith('.'+d))).sort((a,b)=>a.rank-b.rank)[0]||null;
function comparable(a,b){if(!a||!b)return false;const keys=['keyword','location_coordinate','language_code','device','os'];return !keys.some(k=>a.data?.[k]!=null&&b.data?.[k]!=null&&a.data[k]!==b.data[k]);}
function stable(row,business){const h=(row.history||[]).slice(0,-1);if(h.length<3)return null;const last=h.at(-1).positions[business]?.rank;if(last==null)return null;let run=[];for(let i=h.length-1;i>=0;i--){if(h[i].positions[business]?.rank!==last)break;run.unshift(h[i]);}const days=(time(run.at(-1)?.timestamp)-time(run[0]?.timestamp))/86400000;const distinct=new Set(run.map(x=>x.timestamp?.slice(0,10))).size;return distinct>=3&&days>=14?{rank:last,days:Math.floor(days),observations:distinct}:null;}
function analyze(row,companies,business){const a=row.current,b=row.previous;if(!comparable(a,b))return null;const now=a.rank,old=b.rank,reasons=[];let score=0;const peers=companies.filter(c=>c.id!==business).map(c=>{const n=found(a,c),p=found(b,c);return {id:c.id,name:c.name,verified:c.verified!==false,now:n,old:p,delta:n&&p?p.rank-n.rank:null,urlChanged:!!(n&&p&&normal(n.url)!==normal(p.url)),titleChanged:!!(n&&p&&n.title&&p.title&&n.title!==p.title),firstDeep:!!(n&&!p&&n.rank>coverage(b))};});
const delta=now!=null&&old!=null?old-now:null;
if(delta!=null&&Math.abs(delta)>=5){reasons.push('Moved at least 5 positions');score+=Math.abs(delta)+10;}
if(now!=null&&old!=null)for(const edge of [3,10])if((now<=edge)!==(old<=edge)){reasons.push((now<=edge?'Entered':'Left')+' top '+edge);score+=edge===3?12:8;}
const held=stable(row,business);if(delta&&held&&Math.abs(delta)<5){reasons.push('Broke a stable position: '+held.observations+' scans over '+held.days+' days');score+=held.rank===1?25:12;}
if(old!=null&&now==null){reasons.push(coverage(a)>=old?'Previously ranking result missing within checked range':'Previously ranked; current coverage too short to confirm loss');score+=coverage(a)>=old?18:2;}
if(now!=null&&old!=null&&normal(a.url)!==normal(b.url)){reasons.push('Google selected a different page');score+=12;}
const peerMoves=peers.filter(p=>p.delta!=null&&Math.abs(p.delta)>=5);
if(peerMoves.length){reasons.push('Significant competitor movement');score+=8;}
if(!reasons.length)return null;
const opposing=peers.filter(p=>delta!=null&&p.delta!=null&&delta*p.delta<0).sort((x,y)=>Math.abs(y.delta)-Math.abs(x.delta));
const statements=[];
if(delta!=null)statements.push('Your measured position: #'+old+' → #'+now+'.');
else if(old!=null)statements.push('Your earlier #'+old+' result was not returned. Current coverage ends at #'+coverage(a)+'. This is not an exact current rank.');
else if(now!=null)statements.push('Your current position is #'+now+'. '+(now>coverage(b)?'Earlier coverage stopped at #'+coverage(b)+'; this is a first deep observation, not a proven gain.':'Your domain was absent from the earlier returned set; no numerical gain is assigned.'));
else statements.push('Your domain was absent from both returned sets. No numerical movement can be calculated.');
if(normal(a.url)!==normal(b.url)&&a.url&&b.url)statements.push('Your winning URL changed. This establishes a change in Google’s page selection, not when or why the website changed.');
if(opposing.length)statements.push(opposing.slice(0,3).map(p=>p.name+' moved #'+p.old.rank+' → #'+p.now.rank).join('; ')+'. These are opposite movements in the same city/keyword snapshots, not proof that one business caused the other’s loss.');
if(peers.some(p=>p.titleChanged))statements.push('Some search-result titles changed. Google can rewrite titles; this is not verified evidence of an on-page edit.');
statements.push('No paired historical page captures are attached to this analysis. Whether either website changed remains unverified.');
const action=old!=null&&now==null&&coverage(a)<old?'Repeat a comparable scan with sufficient coverage before treating this as a ranking loss.':a.url&&b.url&&normal(a.url)!==normal(b.url)?'Compare the two ranking pages: indexability, canonical/redirects, query intent and internal links. Check dated edits before choosing one focused correction.':'Compare the current winning pages and any recorded edits. Check whether this repeats across related cities/keywords and the next comparable scan before changing the page.';
return {row,business,score,reasons,delta,peers:peers.filter(p=>p.now||p.old).sort((x,y)=>(y.delta!=null&&Math.abs(y.delta)>=5)-(x.delta!=null&&Math.abs(x.delta)>=5)||(x.now?.rank??999)-(y.now?.rank??999)),statements,action,held};}
if(typeof module!=='undefined')module.exports={analyze,stable,comparable};
if(typeof document==='undefined')return;
const expanded=typeof DATA!=='undefined'&&!!DATA.competitors;
const source=typeof DATA!=='undefined'?DATA:null;if(!source)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=u=>/^https?:\/\//.test(u||'')?`<a target="_blank" rel="noopener" href="${esc(u)}">${esc(u)}</a>`:'Not returned';
const names={uwg:'Utah Water Gardens',icon:'Icon Dumpsters',tnt:'TNT Dumpsters'};
const section=document.createElement('section');section.className='detail';section.id='rankingEvents';section.innerHTML='<h2>Flagged ranking events & analysis</h2><p>Automatically compares saved scans. Routine one-position moves are omitted unless they cross the top 3/top 10, change the winning page, or break an established position.</p><details><summary>What gets flagged?</summary><p>Moves of 5+ positions; top-3/top-10 crossings; missing previously ranked results; winning-page changes; competitor moves of 5+ positions. A small move breaks stability only after at least 3 prior dated observations spanning 14 days at the same rank. A stable #1 loss receives higher priority. These are investigation rules, not statistical proof. First deep observations are not gains. New keywords need a second comparable scan.</p></details><label>Flagged business <select id="eventBusiness"></select></label> <label>Event filter <select id="eventFilter"><option value="">All significant events</option><option>Google selected a different page</option><option>Moved at least 5 positions</option><option>Significant competitor movement</option><option value="stable">Broke a stable position</option></select></label><p id="eventCount"></p><div id="eventList"></div><button id="eventMore" hidden>Show more events</button>';
document.getElementById('grid').insertAdjacentElement('beforebegin',section);
const select=document.getElementById('eventBusiness');select.innerHTML=Object.entries(names).filter(([k])=>expanded?k==='uwg':!!source.summary[k]).map(([k,n])=>`<option value="${k}">${n}</option>`).join('');select.value=expanded?'uwg':(window.REPORT_BUSINESS||new URLSearchParams(location.search).get('business')||'icon');
select.closest('label').hidden=true;let companies={},log=[],limit=15;
async function load(){try{if(expanded)companies.uwg=source.competitors;else{for(const [biz,file] of Object.entries({uwg:'local-competitor-data.json',icon:'dumpster-competitor-icon-data.json',tnt:'dumpster-competitor-tnt-data.json'})){if(!source.summary[biz])continue;const r=await fetch(file);if(!r.ok)throw Error();companies[biz]=(await r.json()).companies;}}try{const r=await fetch('website-change-log.json',{cache:'no-store'});if(r.ok)log=(await r.json()).entries||[];}catch{}render();}catch{document.getElementById('eventCount').textContent='Event analysis could not load the saved competitor data. Rankings have not been changed.';}}
function matching(e){return log.filter(x=>x.business===e.business&&x.type!=='Investigation'&&['Applied','Monitoring','Reviewed'].includes(x.status)&&(!x.city||x.city.toLowerCase()===e.row.city.toLowerCase())&&((x.url&&[e.row.current?.url,e.row.previous?.url].map(normal).includes(normal(x.url)))||(x.keyword&&x.keyword.toLowerCase()===e.row.keyword.toLowerCase())));}
function render(){const biz=select.value,filter=document.getElementById('eventFilter').value,rows=source.rows.filter(r=>expanded||r.business===biz),events=rows.map(r=>analyze(r,companies[biz]||[],biz)).filter(Boolean).filter(e=>!filter||e.reasons.some(r=>filter==='stable'?r.startsWith('Broke a stable'):r===filter)).sort((a,b)=>b.score-a.score);document.getElementById('eventCount').textContent=events.length+' flagged searches · Showing '+Math.min(limit,events.length)+'. Stability flags require 3 prior scans over 14 days; two-scan comparisons cannot establish a stable history. Dates below are actual source timestamps.';document.getElementById('eventList').innerHTML=events.slice(0,limit).map((e,i)=>`<details style="border-top:1px solid #ddd;padding-top:10px"><summary>${esc(e.row.city)} · ${esc(e.row.keyword)} · ${e.row.previous?.rank??'NF'} → ${e.row.current?.rank??'NF'} · ${esc(e.reasons[0])}</summary><p><b>${esc(e.reasons.join(' · '))}</b></p><p>${esc(e.row.previous.timestamp)} → ${esc(e.row.current.timestamp)}<br>Organic coverage: #${coverage(e.row.previous)} → #${coverage(e.row.current)}</p>${e.statements.map(s=>`<p>${esc(s)}</p>`).join('')}<p>Previous page: ${link(e.row.previous.url)}<br>Current page: ${link(e.row.current.url)}</p><h3>Recorded website edits</h3>${matching(e).length?matching(e).map(x=>`<p>${esc(x.date)} · ${esc(x.change)}<br>Timing versus these scans must be checked; this is not proof of cause.</p>`).join(''):'<p>No matching applied edit is recorded. This does not mean no edit occurred.</p>'}<h3>Competitor evidence</h3><div style="overflow:auto"><table style="min-width:700px"><thead><tr><th>Business</th><th>Before → now</th><th>Page selection</th><th>Previous → current page</th></tr></thead><tbody>${e.peers.map(p=>`<tr><td>${esc(p.name)}${p.verified?'':' (provisional domain)'}</td><td>${p.old?.rank??'NF'} → ${p.now?.rank??'NF'}${p.firstDeep?' · first deep':''}</td><td>${p.urlChanged?'Different page':p.old&&p.now?'Same page':'Insufficient paired evidence'}</td><td>${link(p.old?.url)}<br>→ ${link(p.now?.url)}</td></tr>`).join('')}</tbody></table></div><p><b>Next action:</b> ${esc(e.action)}</p><button data-event="${i}">Open ranking details</button></details>`).join('')||'<p>No events meet this filter. Small routine changes and unpaired baselines are not promoted to alerts.</p>';section.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const e=events[+b.dataset.event];if(!expanded&&typeof biz!=='undefined'){document.getElementById(e.business)?.click();}if(expanded){document.getElementById('business').value='uwg';show();}detail(e.row);window.ChangeLog?.context({business:e.business,city:e.row.city,keyword:e.row.keyword,urls:[e.row.current?.url,e.row.previous?.url],action:e.action});});document.getElementById('eventMore').hidden=limit>=events.length;}
select.onchange=()=>{limit=15;render()};document.getElementById('eventFilter').onchange=()=>{limit=15;render()};document.getElementById('eventMore').onclick=()=>{limit+=15;render()};for(const k of Object.keys(names))document.getElementById(k)?.addEventListener('click',()=>{select.value=k;limit=15;if(companies[k])render();});load();window.addEventListener('focus',load);
})();
